version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db-container
    ports:
      - 3306:3306
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  web:
    build: ./docker
    container_name: web-container
    ports:
      - 80:80
    volumes:
      - ./dogmeet-laravel-api:/var/www/app
    working_dir: /var/www/app