version: 2.1
jobs:
  test:
    docker:
      - image: circleci/php:8.0.2
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: dogmeet_db_test
          DB_USERNAME: 'root'
          DB_PASSWORD: 'mypass1234'
      - image: circleci/mysql:8.0.20-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: dogmeet_db_test
          MYSQL_USER: 'root'
          MYSQL_ROOT_PASSWORD: 'mypass1234'


    steps:
      - checkout
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql

      - restore_cache:
          name: composer cache
          keys:
            - v1-dependencies-{{ checksum "dogmeet-laravel-api/composer.json" }}
            - v1-dependencies-
      - run:
          working_directory: dogmeet-laravel-api
          command: |
            composer update
      - save_cache:
          key: v1-dependencies-{{ checksum "dogmeet-laravel-api/composer.json" }}
          paths:
            - dogmeet-laravel-api/vendor

      - run:
          name: run cp env file
          working_directory: dogmeet-laravel-api
          command: cp .env.example .env
      - run:
          name: run key generate
          working_directory: dogmeet-laravel-api
          command: php artisan key:generate
      - run:
          name: run migrate
          working_directory: dogmeet-laravel-api
          command: php artisan migrate:fresh --seed --env=testing
      - run:
          working_directory: dogmeet-laravel-api
          name: Run PHPUnit
          command: vendor/bin/phpunit tests/Feature/AreaTest.php

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            ls
            git subtree push --prefix dogmeet-laravel-api/ https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2.1
  #workflow名
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - master
      - deploy:
          requires: # testが成功したら実行する
            - test